# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OTIyYWZjODQ4NWU5NzA2NmY0YjYwNmNlMzYyM2JiY2YzM2EzNGNhYjE0MTYxMGZjYThhYTgyM2FlNThkOWMyNjVlYzI0NDJhNTgzZTIyZTkwMmI2ZGNiNmU1NWRkYzNiZjQxYmE0NjFiMTBlZTc4ZmNjMDY4OTM1NTEyMDFjOGM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
